
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Providers from './providers'
import { ApolloProvider } from './lib/apolloProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({children}: {
  children: React.ReactNode
}) {
    return (
    <html lang="en">
      <body className={inter.className}>
      <ApolloProvider>
        <Providers>{children}</Providers>
      </ApolloProvider>
      </body>
    </html>
  )
}

// apollo provider can only be used in client side components
// app/layout is server side component by default - so we can set apart segments within a server side component to be client side
// by specifying window not undefined, we ensure that section is rendered as client side component
